name: kodecloud-workflow-1

on: push

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
      
      - name: Display Hello World.
        run: echo "Hello, World!"

      - name: Run listing if files.
        run: ls -la

      - name: check Free Memory.
        run: free -h

      - name: Read the file.
        run: cat README.md
